---
- name: ensure jars dir exists
  become: yes
  become_user: root
  file: >-
    path={{java_app_jars_dir}}
    state=directory
    mode=0755
    
- name: download jar...
  become: yes
  become_user: root
  get_url: >-
    url={{java_app_url}}
    dest={{java_app_jars_dir}}/{{java_app_jar}}
    mode=0644

#- name: link uber.jar
#  become: yes
#  become_user: root
#  file: >-
#    src={{java_app_jars_dir}}/{{java_app_jar}}
#    dest={{java_app_jars_dir}}/uber.jar
#    mode=link


